---
- andrelohmann.root_colored_prompt
- andrelohmann.terraform
- andrelohmann.terrahelp
- andrelohmann.terrahelper
- andrelohmann.azurecli
- fanfansama.ansible_amazingtools
- fanfansama.ansible_dockerce4vagrant
...
